version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq-dev
    ports:
      - "5672:5672"   # Порт для передачи сообщений
      - "15672:15672" # Порт веб-интерфейса
    environment:
      RABBITMQ_DEFAULT_USER: andrei
      RABBITMQ_DEFAULT_PASS: ximera
    restart: always