input {
  file {
    path => "/var/log/nginx/*.log"
    start_position => "beginning"
  }
}

filter {
  
  grok {
    match => { "message" => "%{COMBINEDAPACHELOG}" }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "logstash-nginx-%{+YYYY.MM.dd}"
  }
}