---
- name: Setup RabbitMQ Cluster via Docker
  hosts: rmq_servers
  become: true
  tasks:
    - name: Update apt cache and install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Update /etc/hosts with dynamic internal IPs
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      loop:
        - "{{ rmq0_ip }} rmq-0"
        - "{{ rmq1_ip }} rmq-1"

    - name: Remove existing RabbitMQ container
      shell: docker rm -f rabbitmq-server || true

    - name: Run RabbitMQ with Management and Cluster settings
      docker_container:
        name: rabbitmq-server
        image: rabbitmq:3-management
        network_mode: host
        restart_policy: always
        env:
          RABBITMQ_DEFAULT_USER: "admin"
          RABBITMQ_DEFAULT_PASS: "superpassword"
          RABBITMQ_ERLANG_COOKIE: "PETROVSKIY_SECRET_COOKIE" # Одинаковый для всех!
          RABBITMQ_NODENAME: "rabbit@{{ ansible_hostname }}"

    - name: Wait for RabbitMQ to start
      pause:
        seconds: 20

    # Настройка зеркалирования (HA-policy)
    - name: Set HA policy for all queues
      shell: docker exec rabbitmq-server rabbitmqctl set_policy ha-all ".*" '{"ha-mode":"all"}'
      run_once: true # Достаточно запустить на одной ноде

    - name: Install Python3 and Pika
      apt:
        name: [python3, python3-pip]
        state: present

    - name: Install Pika
      pip:
        name: pika
        executable: pip3

    - name: Copy scripts
      copy:
        src: "../{{ item }}"
        dest: "/home/ubuntu/{{ item }}"
        mode: '0755'
      loop:
        - producer.py
        - consumer.py

    - name: Join rmq-1 to cluster
      shell: |
        docker exec rabbitmq-server rabbitmqctl stop_app
        docker exec rabbitmq-server rabbitmqctl join_cluster rabbit@rmq-0
        docker exec rabbitmq-server rabbitmqctl start_app
      when: ansible_host == "111.88.146.207"
      ignore_errors: yes

    - name: Final check of cluster status
      shell: docker exec rabbitmq-server rabbitmqctl cluster_status
      register: cluster_out
      run_once: true

    - name: Show cluster status
      debug:
        msg: "{{ cluster_out.stdout_lines }}"
      run_once: true    